name: Docker Image CI

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'CI:Build' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/mishomihov/go-ethereum:latest && echo $GH_TOKEN | docker login ghcr.io -u USERNAME --password-stdin && docker push ghcr.io/mishomihov/go-ethereum:latest
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
