name: Local Devnet

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'CI:Deploy' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run the local Devnet
      run: |
        docker-compose up -d
        sleep 10

    - name: Deploy HardHat Project
      run: |
        npm install --save-dev hardhat
        npm install @nomicfoundation/hardhat-toolbox --save-dev
        cd hardhat
        echo 'y' | npx hardhat ignition deploy ./ignition/modules/Lock.js --network localhost

    - name: Create snapshot of the Docker Image
      run: |
        docker commit geth-local ghcr.io/mishomihov/go-ethereum:with_contracts_${{ github.run_number }}
        echo $GH_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
        docker push ghcr.io/mishomihov/go-ethereum:with_contracts_${{ github.run_number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run tests againts image with predeployed contracts
      run: |
        cd hardhat
        npx hardhat test --network localhost
